# The URL the site will be built for
base_url = "https://wine79.com"

default_language = "en"
compile_sass = true
title = "Wine79"
description = "Wine79"
generate_feed = false
output_dir = "public"

taxonomies = [
  {name = "tags", paginate_by = 5},
]

theme = 'zolastrap'

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false



[extra]
# Put all your custom variables here
banner = "img/wine_school_top_banner.jpg"
date_format = '%Y-%m-%d'

links = [
	{title = 'Courses', url = '/courses'},
	{title = 'Cellar', url = '/cellar'},
	{title = 'About', url = '/about'},
]

theme = "lux"
themes = ""
schemes = ""
