# The URL the site will be built for
base_url = "https://wine79.com"

default_language = "kr"
compile_sass = true
title = "Wine79.com"
description = "Wine79 와인스쿨"
generate_feed = false
output_dir = "public"

taxonomies = [
  {name = "tags", paginate_by = 100},
]

theme = 'zolastrap'

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false



[extra]
# Put all your custom variables here
banner = "img/wine_school_top_banner.webp"
date_format = '%Y-%m-%d'

links = [
	{title = '포도주 저장실', url = '/cellar'},
	{title = '와인 학교', url = '/school'},
	{title = '에 대한', url = '/about'},
]

theme = "lux"
themes = ""
schemes = ""

[extra.analytics]
google = "G-3ZNB7LZRKL"
